dev:
  container_name: prelurn
  build: .
  env_file: dev.env
  volumes:
    - ./:/opt/prelurn
  command: ["/bin/bash", "--rcfile", "/opt/prelurn/venv/bin/activate"]
test:
  container_name: prelurn
  build: .
  volumes:
    - ./:/opt/prelurn
  command: 'bash run_tests.sh'
docs:
  container_name: prelurn
  build: .
  volumes:
    - ./:/opt/prelurn
  command: 'bash make_docs.sh'