dev:
  container_name: prelurn
  build: .
  env_file: env/dev.env
  volumes:
    - ./:/opt/prelurn
  command: ["/bin/bash", "--rcfile", "/opt/prelurn/venv/bin/activate"]
test:
  container_name: prelurn
  build: .
  env_file: env/dev.env
  volumes:
    - ./:/opt/prelurn
  command: 'bash bin/run_tests.sh'
docs:
  container_name: prelurn
  build: .
  env_file: env/dev.env
  volumes:
    - ./:/opt/prelurn
  command: 'bash bin/make_docs.sh'